version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - POSTGRES_URI=${POSTGRES_URI}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - .:/usr/src/app

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: bishop
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sotsm
    ports:
      - "5432:5432"
